package com.lbg.hr.enums;

public enum CandidateStatus {
    SELECTED,
    ONBOARDING_INITIATED,
    DOCUMENT_REQUESTED,
    DOCUMENT_RECEIVED,
    OFFER_RELEASED,
    OFFER_ACCEPTED,
    BGV_INITIATED,
    BGV_COMPLETED,
    CONFIRM_JOINING_DATE,
    JOINING_DATE_CONFIRMED,
    APPOINTMENT_LETTER_RELEASED,
    RECONFIRM_JOINING_DATE,
    RECONFIRM_RECEIVED,
    JOINING_DATE_RECONFIRMED,
    READY_TO_JOIN,
    CANDIDATE_JOINED,
    CANDIDATE_NOT_JOINED,
    END_ONBOARDING,
    HR_INTERVENTION
}
