from typing import Protocol


class MailSenderProtocol(Protocol):
    def send_mail(self, to: str, subject: str, body: str, reason: str) -> None:
        pass


class SimpleMailSender:
    def send_mail(self, type: str = "", to: str = "", subject: str = "", body: str = "", reason: str = "", values: dict = {}) -> str:
        print(f"Sending mail to {to} for reason '{reason}': {subject}\n{body}")
        if "document_request" == type:
            return "Dear [Candidate's Name],\n\nWe’re pleased to inform you that you’ve been selected for the position of [Job Title] following your recent interview with us at [Company Name]. Congratulations!\n\nTo move forward with the onboarding process, we kindly request you to share the following documents at your earliest convenience:\n\n- Government-issued ID (e.g., Aadhaar, Passport, PAN)\n- Latest educational certificates\n- Previous employment documents (if applicable)\n- Passport-sized photograph\n- Any other documents as discussed during the interview\n\nPlease send scanned copies to [Your Email Address] by [Mention Deadline], so we can initiate the next steps without delay.\n\nShould you have any questions or need assistance, feel free to reach out.\n\nLooking forward to welcoming you aboard!\n\nWarm regards,\nHR Department\nLloyds Technology Center\nHyderabad"
        elif "offer_letter" == type:
            return "Dear [Candidate's Name],\n\nWe are delighted to extend to you the offer for the position of [Job Title] at [Company Name]. Your skills and experience impressed us during the selection process, and we’re excited about the contributions you’ll bring to our team.\n\nAttached to this email, you will find your official offer letter, which includes details about:\n\n- Role and responsibilities\n- Compensation package\n- Start date\n- Reporting manager\n- Additional terms and conditions\n\nPlease review the document thoroughly and let us know your acceptance by replying to this email or signing and returning the offer letter by [Offer Acceptance Deadline].\n\nShould you have any questions or need clarifications, feel free to get in touch. We look forward to having you onboard and beginning a fruitful journey together.\n\nWarm regards,\n[Your Full Name]\n[Your Designation]\n[Company Name]\n[Contact Information]"
        elif "initiate_bgv" == type:
            return "Dear BGV Team,\n\nWe would like to initiate the background verification process for the below candidate who has been offered the position of [Job Title] at [Company Name]. Please find the details and attached documents required for verification:\n\n- Candidate Name: [Candidate's Name]\n- Position: [Job Title]\n- Joining Date: [Proposed Start Date]\n- Offer Letter: Attached\n- Government-issued ID: Attached\n- Educational Certificates: Attached\n- Employment Records (if applicable): Attached\n\nKindly proceed with the verification and keep us updated with the status. If any additional information is required, feel free to reach out.\n\nThank you for your support in completing the onboarding formalities.\n\nBest regards,\n[Your Full Name]\nHR Team\n[Company Name]\n[Contact Information]"
        elif "confirm_joining_date" == type:
            return "Dear [Candidate's Name],\n\nWe’re pleased to inform you that your background verification process has been successfully completed. Thank you for your prompt submission of all required documents and your cooperation throughout the process.\n\nWe are excited to welcome you to [Company Name]! Please find below the details of your joining:\n\n- Position: [Job Title]\n- Joining Date: [Confirmed Start Date]\n- Reporting Time & Location: [Time], [Office Address or Virtual Onboarding Details]\n- Point of Contact: [Onboarding Coordinator's Name & Contact Info]\n\nKindly confirm your availability for the mentioned date and let us know if you require any assistance or clarification prior to onboarding.\n\nLooking forward to having you onboard and beginning a successful journey together.\n\nWarm regards,\n[Your Full Name]\nHR Team\n[Company Name]\n[Contact Information]"
        elif "appointment_letter" == type:
            return "Dear [Candidate's Name],\n\nWe are pleased to formally offer you the position of [Job Title] at [Company Name], effective from [Joining Date]. This appointment is based on your qualifications, performance during the selection process, and mutual alignment with our organizational goals.\n\nThe key details of your appointment are as follows:\n\n- Position: [Job Title]\n- Reporting Manager: [Manager's Name]\n- Department: [Department Name]\n- Location: [Office Location or Remote Work Details]\n- Start Date: [Joining Date]\n- Compensation: As per the offer letter provided\n- Working Hours: [Standard Working Hours or as per business needs]\n- Probation Period: [Mention Duration, if applicable]\n\nPlease review the attached appointment letter for detailed terms and conditions. By signing and returning the letter, you acknowledge your acceptance of the role and agreement to abide by the company policies and practices.\n\nWe are excited to welcome you to our team and look forward to a successful association.\n\nWarm regards,\n[Your Full Name]\nHR Team\n[Company Name]\n[Contact Information]"
        elif "reconfirm_joing_date" == type:
            return "Dear [Candidate's Name],\n\nWe hope you're doing well.\n\nThis is a gentle reminder to reconfirm your joining date for the position of [Job Title] at [Company Name], scheduled for [Confirmed Start Date]. We are looking forward to welcoming you and beginning a rewarding journey together.\n\nPlease respond to this email confirming your availability, and let us know if you have any queries regarding the reporting details, onboarding documents, or other formalities.\n\nDetails:\n- Position: [Job Title]\n- Joining Date: [Confirmed Start Date]\n- Reporting Time & Location: [Time], [Office Address or Virtual Instructions]\n\nWishing you a smooth transition, and we’re excited to have you onboard!\n\nWarm regards,\n[Your Full Name]\nHR Team\n[Company Name]\n[Contact Information]"
        else:
            return "Mail sent successfully."


mail_sender: MailSenderProtocol = SimpleMailSender()
