spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/talentbot-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: workflow-manager

server:
  port: 8082
hrService:
  url: "http://localhost:8000"

post:
  api:
    initendpoint: "http://localhost:8000/init"
    resumeendpoint: "http://localhost:8000/resume"